main: com.rayzr522.minecraftmarkdown.MinecraftMarkdown
name: MinecraftMarkdown
version: 1.0
description: A bukkit plugin allowing configurable Markdown-like formatting
author: [Rayzr]
commands:
    minecraftmarkdown:
        description: "Admin command for \u00a7bMinecraftMarkdown"
        aliases: [mm,markdown]
        usage: "\u00a77Usage: \u00a7b/minecraftmarkdown [reload]"
        permission: MinecraftMarkdown.admin
